# Generated by Django 3.1 on 2020-08-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Registration',
            fields=[
                ('BookID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('BookName', models.CharField(max_length=50)),
                ('Author1', models.CharField(max_length=100)),
                ('Author2', models.CharField(max_length=100)),
                ('Publisher', models.CharField(max_length=100)),
                ('Page', models.CharField(max_length=10)),
                ('Price', models.CharField(max_length=10)),
                ('BookBelongsCourse', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty_Registration',
            fields=[
                ('Faculty_Registration_Number', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('Phone1', models.CharField(max_length=15)),
                ('Phone2', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=10)),
                ('Current_Address', models.CharField(max_length=200)),
                ('Permanent_Address', models.CharField(max_length=200)),
                ('Branch', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Registration',
            fields=[
                ('Student_Registration_Number', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('Phone1', models.CharField(max_length=15)),
                ('Phone2', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=10)),
                ('Current_Address', models.CharField(max_length=200)),
                ('Permanent_Address', models.CharField(max_length=200)),
                ('Course', models.CharField(max_length=20)),
                ('Year', models.CharField(max_length=10)),
                ('Branch', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=10)),
            ],
        ),
    ]
