# Generated by Django 3.1 on 2020-09-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Issue_Student',
            fields=[
                ('Student_Registration_Number', models.CharField(max_length=10)),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('Phone1', models.CharField(max_length=15)),
                ('Phone2', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=10)),
                ('Current_Address', models.CharField(max_length=200)),
                ('Permanent_Address', models.CharField(max_length=200)),
                ('Course', models.CharField(max_length=20)),
                ('Year', models.CharField(max_length=10)),
                ('Branch', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=10)),
                ('BookID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('BookName', models.CharField(max_length=50)),
                ('Author1', models.CharField(max_length=100)),
                ('Author2', models.CharField(max_length=100)),
                ('Publisher', models.CharField(max_length=100)),
                ('Page', models.CharField(max_length=10)),
                ('Price', models.CharField(max_length=10)),
                ('BookBelongsCourse', models.CharField(max_length=50)),
                ('Book_Issue_To_Student_Date', models.CharField(max_length=30)),
            ],
        ),
    ]
