# Generated by Django 3.1 on 2020-11-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSapp', '0002_book_issue_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_issue_student',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book_issue_student',
            name='BookID',
            field=models.CharField(max_length=20),
        ),
    ]
